// <auto-generated />
namespace HouseholdServices.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Adddata : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Adddata));
        
        string IMigrationMetadata.Id
        {
            get { return "201804022252587_Add-data"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
